# Generated by Django 3.2.5 on 2021-07-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=170, unique=True)),
                ('slug', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Citi',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Prof_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=170, unique=True)),
                ('_slug', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
    ]
